// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: cases/layout/args.gohtml

package layout

import (
	"io"
	"strconv"
	"strings"
	"zfw/models"
)

func Args(objs ...*models.Widget) string {
	var _b strings.Builder

	_objs := func(_buffer io.StringWriter) {
		_buffer.WriteString(objs)
	}

	RenderArgs(&_b, _objs)
	return _b.String()
}

func RenderArgs(_buffer io.StringWriter, objs ...*models.Widget) {

	size := strconv.Itoa(12 / len(objs))

}
