// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/argsbug.gohtml

package cases

import (
	"cases/layout/args"
	"github.com/sipin/gorazor/gorazor"
	"io"
	. "kp/models"
	"strings"
	"tpl/helper"
)

// Argsbug generates cases/argsbug.gohtml
func Argsbug(totalMessage int, u *User) string {
	var _b strings.Builder
	RenderArgsbug(&_b, totalMessage, u)
	return _b.String()
}

// RenderArgsbug render cases/argsbug.gohtml
func RenderArgsbug(_buffer io.StringWriter, totalMessage int, u *User) {

	messages := []string{}

	// Line: 13
	_buffer.WriteString("\n\n<p>")
	// Line: 15
	_buffer.WriteString(gorazor.HTMLEscape(gorazor.Itoa(args(messages...))))
	// Line: 15
	_buffer.WriteString("</p>")

}
