// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/blk.gohtml

package cases

import (
	"io"
	"strings"
)

// Blk generates cases/blk.gohtml
func Blk() string {
	var _b strings.Builder
	RenderBlk(&_b)
	return _b.String()
}

// RenderBlk render cases/blk.gohtml
func RenderBlk(_buffer io.StringWriter) {

}
