// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/bug.gohtml

package cases

import (
	"io"
	"strings"
)

// Bug generates cases/bug.gohtml
func Bug() string {
	var _b strings.Builder
	RenderBug(&_b)
	return _b.String()
}

// RenderBug render cases/bug.gohtml
func RenderBug(_buffer io.StringWriter) {
	// Line: 1
	_buffer.WriteString("<html>\n  <head>\n    <title>Title</title>\n  </head>\n\n  <body>\n  Body\n  </body>\n</html>")

}
