// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: cases/bug34.gohtml

package cases

import (
	"io"
	"strings"
)

func Bug34() string {
	var _b strings.Builder
	RenderBug34(&_b)
	return _b.String()
}

func RenderBug34(_buffer io.StringWriter) {
	_buffer.WriteString("value=\\\"<?= h(aabasdf\\Admin\\Document::$asdf) ?>\\\"/>\\n")

}
