// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/bug34.gohtml

package cases

import (
	"io"
	"strings"
)

// Bug34 generates cases/bug34.gohtml
func Bug34() string {
	var _b strings.Builder
	RenderBug34(&_b)
	return _b.String()
}

// RenderBug34 render cases/bug34.gohtml
func RenderBug34(_buffer io.StringWriter) {
	_buffer.WriteString("value=\\\"<?= h(aabasdf\\Admin\\Document::$asdf) ?>\\\"/>\\n")

}
