// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/bug9.gohtml

package cases

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Bug9 generates cases/bug9.gohtml
func Bug9(l *Locale) string {
	var _b strings.Builder
	RenderBug9(&_b, l)
	return _b.String()
}

// RenderBug9 render cases/bug9.gohtml
func RenderBug9(_buffer io.StringWriter, l *Locale) {
	// Line: 3
	_buffer.WriteString("\n<span>")
	// Line: 4
	_buffer.WriteString(gorazor.HTMLEscape(l.T(`for`)))
	// Line: 4
	_buffer.WriteString("</span>")

}
