// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/codeblock.gohtml

package cases

import (
	"io"
	"strings"
)

// Codeblock generates cases/codeblock.gohtml
func Codeblock() string {
	var _b strings.Builder
	RenderCodeblock(&_b)
	return _b.String()
}

// RenderCodeblock render cases/codeblock.gohtml
func RenderCodeblock(_buffer io.StringWriter) {

}
