// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/email.gohtml

package cases

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Email generates cases/email.gohtml
func Email() string {
	var _b strings.Builder
	RenderEmail(&_b)
	return _b.String()
}

// RenderEmail render cases/email.gohtml
func RenderEmail(_buffer io.StringWriter) {
	// Line: 1
	_buffer.WriteString("<span>rememberingsteve@apple.com ")
	// Line: 1
	_buffer.WriteString(gorazor.HTMLEscape(username))
	// Line: 1
	_buffer.WriteString("</span>")

}
