// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/footer.gohtml

package cases

import (
	"io"
	"strings"
)

// Footer generates cases/footer.gohtml
func Footer() string {
	var _b strings.Builder
	RenderFooter(&_b)
	return _b.String()
}

// RenderFooter render cases/footer.gohtml
func RenderFooter(_buffer io.StringWriter) {
	// Line: 1
	_buffer.WriteString("<div>copyright 2014</div>")

}
