// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/forward.gohtml

package cases

import (
	"cases/layout"
	"io"
	"strings"
)

// Forward generates cases/forward.gohtml
func Forward(content string, err string) string {
	var _b strings.Builder
	RenderForward(&_b, content, err)
	return _b.String()
}

// RenderForward render cases/forward.gohtml
func RenderForward(_buffer io.StringWriter, content string, err string) {

	_body := func(_buffer io.StringWriter) {

		//hello word
		/* hello this */

	}

	layout.RenderBase(_buffer, _body, nil, nil)
}
