// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/header.gohtml

package cases

import (
	"io"
	"strings"
)

// Header generates cases/header.gohtml
func Header() string {
	var _b strings.Builder
	RenderHeader(&_b)
	return _b.String()
}

// RenderHeader render cases/header.gohtml
func RenderHeader(_buffer io.StringWriter) {
	// Line: 1
	_buffer.WriteString("<div>Page Header</div>")

}
