// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/keyword.gohtml

package cases

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Keyword generates cases/keyword.gohtml
func Keyword() string {
	var _b strings.Builder
	RenderKeyword(&_b)
	return _b.String()
}

// RenderKeyword render cases/keyword.gohtml
func RenderKeyword(_buffer io.StringWriter) {
	// Line: 1
	_buffer.WriteString("BLK(<span>rememberingsteve@apple.com ")
	// Line: 1
	_buffer.WriteString(gorazor.HTMLEscape(username))
	// Line: 1
	_buffer.WriteString("</span>)BLK")

}
