// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/layout.gohtml

package cases

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Layout generates cases/layout.gohtml
func Layout(body string, title string, side string) string {
	var _b strings.Builder
	RenderLayout(&_b, body, title, side)
	return _b.String()
}

// RenderLayout render cases/layout.gohtml
func RenderLayout(_buffer io.StringWriter, body string, title string, side string) {
	// Line: 5
	_buffer.WriteString("\n<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\" />")
	// Line: 10
	_buffer.WriteString(gorazor.HTMLEscape(title))
	// Line: 10
	_buffer.WriteString("\n</head>\n<body>\n<div>")
	// Line: 13
	_buffer.WriteString(gorazor.HTMLEscape(body))
	// Line: 13
	_buffer.WriteString("</div>\n<div>")
	// Line: 14
	_buffer.WriteString(gorazor.HTMLEscape(side))
	// Line: 14
	_buffer.WriteString("</div>\n</body>\n</html>")

}
