// This file is generated by gorazor 1.2.1
// DON'T modified manually
// Should edit source file and re-generate: cases/scopebug.gohtml

package cases

import (
	"dm"
	"io"
	"strings"
	"zfw/models"
	. "zfw/tplhelper"
)

// Scopebug generates cases/scopebug.gohtml
func Scopebug(obj *models.Widget) string {
	var _b strings.Builder
	RenderScopebug(&_b, obj)
	return _b.String()
}

// RenderScopebug render cases/scopebug.gohtml
func RenderScopebug(_buffer io.StringWriter, obj *models.Widget) {

	if 1 == 2 {
	} else {
		values := []int{}
		for _, v := range values {
			if v, ok := v.(type); ok {

				// Line: 16
				_buffer.WriteString("<a>\n\t\t\t\t\t")
				for _, v := range values {
				}
				// Line: 18
				_buffer.WriteString("\n\t\t\t\t</a>")

			} else {

			}
		}
	}

}
