// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/sectionbug.gohtml

package cases

import (
	"cases/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"kp/models"
	"strings"
)

// Sectionbug generates cases/sectionbug.gohtml
func Sectionbug() string {
	var _b strings.Builder
	RenderSectionbug(&_b)
	return _b.String()
}

// RenderSectionbug render cases/sectionbug.gohtml
func RenderSectionbug(_buffer io.StringWriter) {

	_body := func(_buffer io.StringWriter) {

	}

	_js := func(_buffer io.StringWriter) {
		for _, jsFile := range ctx.GetJS() {

			// Line: 12
			_buffer.WriteString("<script src=\"")
			// Line: 12
			_buffer.WriteString(gorazor.HTMLEscape(jsFile))
			// Line: 12
			_buffer.WriteString("\"></script>")

		}

	}

	layout.RenderBase(_buffer, _body, nil, _js)
}
