// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: cases/slashbug.gohtml

package cases

import (
	"io"
	"strconv"
	"strings"
	"zfw/models"
)

// Slashbug generates cases/slashbug.gohtml
func Slashbug(objs ...*models.Widget) string {
	var _b strings.Builder
	RenderSlashbug(&_b, objs)
	return _b.String()
}

// RenderSlashbug render cases/slashbug.gohtml
func RenderSlashbug(_buffer io.StringWriter, objs ...*models.Widget) {

	size := strconv.Itoa(12 / len(objs))

}
