// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: cases/var.gohtml

package cases

import (
	"io"
	"strings"
)

// Var generates cases/var.gohtml
func Var(totalMessage int) string {
	var _b strings.Builder
	RenderVar(&_b, totalMessage)
	return _b.String()
}

// RenderVar render cases/var.gohtml
func RenderVar(_buffer io.StringWriter, totalMessage int) {

}
