// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: cases/codeblock.gohtml

package cases

import (
	"io"
	"strings"
)

func Codeblock() string {
	var _b strings.Builder
	RenderCodeblock(&_b)
	return _b.String()
}

func RenderCodeblock(_buffer io.StringWriter) {

}
