// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: cases/edit.gohtml

package cases

import (
	"cases/layout"
	"github.com/sipin/gorazor/gorazor/"
	"io"
	"kp/models"
	"strings"
)

func Edit(u *models.User) string {
	var _b strings.Builder
	RenderEdit(&_b, u)
	return _b.String()
}

func RenderEdit(_buffer io.StringWriter, u *models.User) {

	_body := func(_buffer io.StringWriter) {
		_buffer.WriteString("\n<div style=\"width: 500px\">\n<form role=\"form\">\n  <div class=\"form-group\">\n    <label for=\"exampleInputEmail1\">名字</label>\n    <input type=\"email\" class=\"form-control\" id=\"exampleInputEmail1\" placeholder=\"Enter email\" value=\"")
		_buffer.WriteString(gorazor.HTMLEscape(u.Name))
		_buffer.WriteString("\">\n  </div>\n  <div class=\"form-group\">\n    <label for=\"exampleInputPassword1\">电邮</label>\n    <input type=\"email\" class=\"form-control\" id=\"exampleInputPassword1\" placeholder=\"电邮\" value=\"")
		_buffer.WriteString(gorazor.HTMLEscape(u.Email))
		_buffer.WriteString("\">\n  </div>\n  <button type=\"submit\" class=\"btn btn-primary\">保存</button>\n  <a href=\"/admin/user\" class=\"btn btn-default pull-right\">返回</a>\n</form>\n</div>")

	}

	_title := func(_buffer io.StringWriter) {

		_buffer.WriteString("用户管理")

	}

	layout.RenderBase(_buffer, _body, _title, nil)
}
