// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: /cases/blk.gohtml

package cases

import (
	"bytes"
	"io"
	"strings"
)

func Blk() string {
	var _b strings.Builder
	RenderBlk(&_b)
	return _b.String()
}

func RenderBlk(_buffer io.StringWriter) {

}
