// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: cases/escapebug.gohtml

package cases

import (
	"bytes"
	"io"
	"strings"
)

func Escapebug() string {
	var _b strings.Builder
	RenderEscapebug(&_b)
	return _b.String()
}

func RenderEscapebug(_buffer io.StringWriter) {
	_buffer.WriteString("<script type=\"text/javascript\">console.log(\"\\n\");</script>")

}
