// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: cases/import.gohtml

package cases

import (
	"hello"
	"huhu"
	"io"
	"now"
	"strconv"
	"strings"
	"this"
)

func Import() string {
	var _b strings.Builder
	RenderImport(&_b)
	return _b.String()
}

func RenderImport(_buffer io.StringWriter) {
	_buffer.WriteString("\n\n\n<p>hello</p>")

}
