// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: /cases/layout.gohtml

package cases

import (
	"bytes"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

func Layout(body string, title string, side string) string {
	var _b strings.Builder
	RenderLayout(&_b, body, title, side)
	return _b.String()
}

func RenderLayout(_buffer io.StringWriter, body string, title string, side string) {
	_buffer.WriteString("\n<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\" />")
	_buffer.WriteString(gorazor.HTMLEscape(title))
	_buffer.WriteString("\n</head>\n<body>\n<div>")
	_buffer.WriteString(gorazor.HTMLEscape(body))
	_buffer.WriteString("</div>\n<div>")
	_buffer.WriteString(gorazor.HTMLEscape(side))
	_buffer.WriteString("</div>\n</body>\n</html>")

}
