// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: cases/quote.gohtml

package cases

import (
	"bytes"
	"io"
	"strings"
)

func Quote() string {
	var _b strings.Builder
	RenderQuote(&_b)
	return _b.String()
}

func RenderQuote(_buffer io.StringWriter) {
	_buffer.WriteString("<html>'text'</html>")

}
