// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: cases/var.gohtml

package cases

import (
	"io"
	"strings"
)

func Var(totalMessage int) string {
	var _b strings.Builder
	RenderVar(&_b, totalMessage)
	return _b.String()
}

func RenderVar(_buffer io.StringWriter, totalMessage int) {

}
