// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: tests/tpl/index.gohtml

package tpl

import (
	"github.com/sipin/gorazor/gorazor"
	"github.com/sipin/gorazor/tests/data"
	"io"
	"strings"
)

func Index(rows []data.BenchRow) string {
	var _b strings.Builder
	RenderIndex(&_b, rows)
	return _b.String()
}

func RenderIndex(_buffer io.StringWriter, rows []data.BenchRow) {
	_buffer.WriteString("\n<html>\n\t<head><title>test</title></head>\n\t<body>\n\t\t<ul>\n\t\t")
	for _, row := range rows {
		if row.Print {

			_buffer.WriteString("<li>ID=")
			_buffer.WriteString(gorazor.HTMLEscInt(row.ID))
			_buffer.WriteString(", Message=")
			_buffer.WriteString(gorazor.HTMLEscStr(row.Message))
			_buffer.WriteString("</li>")

		}
	}
	_buffer.WriteString("\n\t\t</ul>\n\t</body>\n</html")

}
