// This file is generated by gorazor 2.0.1
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/home.gohtml

package tpl

import (
	"github.com/sipin/gorazor/examples/models"
	"github.com/sipin/gorazor/examples/tpl/helper"
	"github.com/sipin/gorazor/examples/tpl/layout"
	"github.com/sipin/gorazor/pkg/gorazor"
	"io"
	"strings"
)

func Home(totalMessage int, u *models.User) string {
	var _b strings.Builder
	RenderHome(&_b, totalMessage, u)
	return _b.String()
}

func RenderHome(_buffer io.StringWriter, totalMessage int, u *models.User) {

	_body := func(_buffer io.StringWriter) {
		_buffer.WriteString((helper.Header()))
		_buffer.WriteString((helper.Msg(u)))

	}

	_title := func(_buffer io.StringWriter) {

		_buffer.WriteString("<title>")
		_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
		_buffer.WriteString("'s homepage</title>")

	}

	_side := func(_buffer io.StringWriter) {
		switch totalMessage {
		case 0:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has no message</p>")

		case 1:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has 1 messages</p>")

		default:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has ")
			_buffer.WriteString(gorazor.HTMLEscInt(totalMessage))
			_buffer.WriteString(" messages</p>")

		}

	}

	layout.RenderBase(_buffer, _body, _title, _side)
}
