// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/home.gohtml

package tpl

import (
	"github.com/sipin/gorazor/examples/models"
	"github.com/sipin/gorazor/examples/tpl/helper"
	"github.com/sipin/gorazor/examples/tpl/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

// Home generates examples/tpl/home.gohtml
func Home(totalMessage int, u *models.User) string {
	var _b strings.Builder
	RenderHome(&_b, totalMessage, u)
	return _b.String()
}

// RenderHome render examples/tpl/home.gohtml
func RenderHome(_buffer io.StringWriter, totalMessage int, u *models.User) {

	_body := func(_buffer io.StringWriter) {
		// Line: 13
		_buffer.WriteString((helper.Header()))
		// Line: 14
		_buffer.WriteString((helper.Msg(u)))

	}

	_title := func(_buffer io.StringWriter) {

		// Line: 17
		_buffer.WriteString("<title>")
		// Line: 17
		_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
		// Line: 17
		_buffer.WriteString("'s homepage</title>")

	}

	_side := func(_buffer io.StringWriter) {
		switch totalMessage {
		case 0:

			// Line: 23
			_buffer.WriteString("<p>")
			// Line: 23
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			// Line: 23
			_buffer.WriteString(" has no message</p>")

		case 1:

			// Line: 25
			_buffer.WriteString("<p>")
			// Line: 25
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			// Line: 25
			_buffer.WriteString(" has 1 messages</p>")

		default:

			// Line: 27
			_buffer.WriteString("<p>")
			// Line: 27
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			// Line: 27
			_buffer.WriteString(" has ")
			// Line: 27
			_buffer.WriteString(gorazor.HTMLEscInt(totalMessage))
			// Line: 27
			_buffer.WriteString(" messages</p>")

		}

	}

	layout.RenderBase(_buffer, _body, _title, _side)
}
