// This file is generated by gorazor 2.0
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/home.gohtml

package tpl

import (
	"github.com/sipin/gorazor/examples/models"
	"github.com/sipin/gorazor/examples/tpl/helper"
	"github.com/sipin/gorazor/examples/tpl/layout"
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
)

func Home(totalMessage int, u *models.User) string {
	var _b strings.Builder
	RenderHome(&_b, totalMessage, u)
	return _b.String()
}

func RenderHome(_buffer io.StringWriter, totalMessage int, u *models.User) {

	_body := func(_buffer io.StringWriter) {
		_buffer.WriteString((helper.Header()))
		_buffer.WriteString((helper.Msg(u)))
		for i := 0; i < 2; i++ {
			if totalMessage > 0 {
				if totalMessage == 1 {

					_buffer.WriteString("<p>")
					_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
					_buffer.WriteString(" has 1 message</p>")

				} else {

					_buffer.WriteString("<p>")
					_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
					_buffer.WriteString(" has ")
					_buffer.WriteString(gorazor.HTMLEscStr(gorazor.Itoa(totalMessage)))
					_buffer.WriteString(" messages</p>")

				}
			} else {

				_buffer.WriteString("<p>")
				_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
				_buffer.WriteString(" has no messages</p>")

			}
		}

		for i := 0; i < 2; i++ {
			if totalMessage > 0 {
				if totalMessage == 1 {

					_buffer.WriteString("<p>")
					_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
					_buffer.WriteString(" has 1 message</p>")

				} else {

					_buffer.WriteString("<p>")
					_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
					_buffer.WriteString(" has ")
					_buffer.WriteString(gorazor.HTMLEscStr(gorazor.Itoa(totalMessage)))
					_buffer.WriteString(" messages</p>")

				}
			} else {

				_buffer.WriteString("<p>")
				_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
				_buffer.WriteString(" has no messages</p>")

			}
		}

		switch totalMessage {
		case 1:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has 1  message</p>")

		case 2:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has 2 messages</p>")

		default:

			_buffer.WriteString("<p>")
			_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
			_buffer.WriteString(" has no messages</p>")

		}

		_buffer.WriteString((helper.Footer()))

	}

	_title := func(_buffer io.StringWriter) {

		_buffer.WriteString("<title>")
		_buffer.WriteString(gorazor.HTMLEscStr(u.Name))
		_buffer.WriteString("'s homepage</title>")

	}

	_side := func(_buffer io.StringWriter) {

	}

	layout.RenderBase(_buffer, _body, _title, _side)
}
