// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: docs/hello/tpl/index.gohtml

package tpl

import (
	"github.com/sipin/gorazor/gorazor"
	"io"
	"strings"
	"time"
)

// Index generates docs/hello/tpl/index.gohtml
func Index() string {
	var _b strings.Builder
	RenderIndex(&_b)
	return _b.String()
}

// RenderIndex render docs/hello/tpl/index.gohtml
func RenderIndex(_buffer io.StringWriter) {
	// Line: 5
	_buffer.WriteString("\n\n<p>This is Index</p>")

	t := time.Now()
	StrTime := t.Format("2006-01-02 15:04:05")

	// Line: 12
	_buffer.WriteString("<p>Time now is:  ")
	// Line: 12
	_buffer.WriteString(gorazor.HTMLEscStr(StrTime))
	// Line: 12
	_buffer.WriteString(" </p>")

}
