// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: examples/tpl/layout/base.gohtml

package layout

import (
	"io"
	"strings"
)

// Base generates examples/tpl/layout/base.gohtml
func Base(body string, title string, side string) string {
	var _b strings.Builder

	_body := func(_buffer io.StringWriter) {
		_buffer.WriteString(body)
	}

	_title := func(_buffer io.StringWriter) {
		_buffer.WriteString(title)
	}

	_side := func(_buffer io.StringWriter) {
		_buffer.WriteString(side)
	}

	RenderBase(&_b, _body, _title, _side)
	return _b.String()
}

// RenderBase render examples/tpl/layout/base.gohtml
func RenderBase(_buffer io.StringWriter, body func(_buffer io.StringWriter), title func(_buffer io.StringWriter), side func(_buffer io.StringWriter)) {
	// Line: 5
	_buffer.WriteString("\n<!DOCTYPE html>\n<html>\n<head>\n<meta charset=\"utf-8\" />")
	// Line: 10
	title(_buffer)
	// Line: 10
	_buffer.WriteString("\n</head>\n<body>\n<div style=\"width: 960px\">\n\t<div style=\"float: left; width: 460px\">")
	// Line: 14
	body(_buffer)
	// Line: 14
	_buffer.WriteString("</div>\n\t<div style=\"float: right; width: 200px\">")
	// Line: 15
	side(_buffer)
	// Line: 15
	_buffer.WriteString("</div>\n</div>\n</body>\n</html>")

}
