// This file is generated by gorazor 1.2.2
// DON'T modified manually
// Should edit source file and re-generate: pkg/razorcore/ctxcases/escaping.gohtml

package ctxcases

import (
	gorazor "github.com/sipin/gorazor/runtime"
	"io"
	"strings"
)

// Escaping generates pkg/razorcore/ctxcases/escaping.gohtml
func Escaping(url string, q string, name string) string {
	var _b strings.Builder
	RenderEscaping(&_b, url, q, name)
	return _b.String()
}

// RenderEscaping render pkg/razorcore/ctxcases/escaping.gohtml
func RenderEscaping(_buffer io.StringWriter, url string, q string, name string) {
	// Line: 5
	_buffer.WriteString("\n<a href=\"")
	// Line: 6
	_buffer.WriteString(gorazor.URLEscape(url))
	// Line: 6
	_buffer.WriteString("\">link</a>\n<a href=\"/search?q=")
	// Line: 7
	_buffer.WriteString(gorazor.URLQueryEscape(q))
	// Line: 7
	_buffer.WriteString("\">search</a>\n<img src=\"")
	// Line: 8
	_buffer.WriteString(gorazor.URLEscape(url))
	// Line: 8
	_buffer.WriteString("\" alt=\"")
	// Line: 8
	_buffer.WriteString(gorazor.HTMLEscStr(name))
	// Line: 8
	_buffer.WriteString("\">\n<script>\nvar n = \"")
	// Line: 10
	_buffer.WriteString(gorazor.JSEscape(name))
	// Line: 10
	_buffer.WriteString("\";\nfor (var i = 0; i < 10; i++) { if (i < 5) { log(n); } }\n</script>\n<p>")
	// Line: 13
	_buffer.WriteString(gorazor.HTMLEscStr(name))
	// Line: 13
	_buffer.WriteString("</p>")

}
